SMfarmacia/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.contrib.auth.views import login, logout
from reportes.views import ReportePacientesPDF, ReporteMedicamentosPDF
from Registro import views

from django.contrib.auth.decorators import login_required

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),


    #------------------------FRONT INICIAL------------------------------------------------------#
    url(r'^$', login, {'template_name': 'index.html', }, name="login_index"),
    url(r'^mision/$', 'home.views.mision', name='Mision'),
    url(r'^vision/$', 'home.views.vision', name='Vision'),
    url(r'^quienes_somos/$', 'home.views.quienes_somos', name='Quienes_Somos'),
    #-------------------------------------------------------------------------------------------#
    

    #------------------------PRELOADER----------------------------------------------------------#
    url(r'^preloader/$', 'home.views.preloader', name='preloader'),
    #-------------------------------------------------------------------------------------------#
    

    #------------------------FRONT SECUNDARIO---------------------------------------------------#
    url(r'^home/$', 'home.views.home', name='home'),
        url(r'^logout/$', logout, {'template_name': 'logout.html', }, name="logout"),
        url(r'^signup/$', 'home.views.signup', name='signup'),
        url(r'^signup/success/$', 'home.views.register_success', name="success_signup"),
    #-------------------------------------------------------------------------------------------#


    #-------------------------PACIENTES---------------------------------------------------------#
    url(r'^pacientes/$', 'Registro.views.paciente', name="rg_pacientes"),
        url(r'^mtr_pacientes/$', 'Registro.views.mostrar_pacientes', name="mtr_pacientes"), 
        url(r'^pacientes/(?P<pk>\d+)/editar/$', views.UpdatePaciView.as_view(), name='editar_paci'),
        url(r'^pacientes/(?P<pk>\d+)/eliminar/$', views.eliminar_pacientes, name='eliminar_paci'),  
    #-------------------------------------------------------------------------------------------#


    #-------------------------MEDICAMENTOS------------------------------------------------------#
    url(r'^medicamentos/$', 'Registro.views.medicamento', name="rg_medicamentos"),
        url(r'^mtr_medicamentos/$', 'Registro.views.mostrar_medicamentos', name="mostrar_medicamentos"), 
        url(r'^medicinas_habiles/$', 'Registro.views.mostrar_medi_index', name="mostrar_medicamentos_index"),
        url(r'^medicamentos/(?P<pk>\d+)/editar/$', views.UpdateMediView.as_view(), name='editar_medicamentos'),
        url(r'^medicamentos/(?P<pk>\d+)/eliminar/$', views.eliminar_medicamentos, name='eliminar_medicamentos'),  
    #-------------------------------------------------------------------------------------------#


    #-------------------------SERVICIOS---------------------------------------------------------#
    url(r'^servicios/$', 'Registro.views.servicio', name="rg_servicios"),
        url(r'^mtr_servicios/$','Registro.views.mostrar_servicio', name='mostrar_servicio'),
    #-------------------------------------------------------------------------------------------#


    #-------------------------MANUAL DE USUARIOS------------------------------------------------#
    url(r'^ayuda/$', 'reportes.views.ayuda'),
    #-------------------------------------------------------------------------------------------#


    #-------------------------REPORTE IMPORTANTE------------------------------------------------#
    url(r'^reporte_pacientes_pdf/$',login_required(ReportePacientesPDF.as_view())),
    url(r'^reporte_medicamentos_pdf/$',login_required(ReporteMedicamentosPDF.as_view())),
    url(r'^change_views/', 'reportes.views.pdf_view'),
    #-------------------------------------------------------------------------------------------#
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Registro/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

class pacientes(models.Model):
	cedula = models.CharField(max_length=10, null=True, blank=True, unique=True)
	nombre_paci = models.CharField(max_length=50, null=True)
	apellido_paci = models.CharField(max_length=50, null=True)
	cod_movil = models.IntegerField()
	movil = models.IntegerField()
	cod_tlf = models.IntegerField()
	tlf = models.IntegerField()
	direccion_paci = models.TextField(max_length=255, null=True)
	fech_naci = models.DateField(null=True)
	tiempo_registro_paciente = models.DateTimeField(auto_now_add=True, auto_now=False)
	actualizado_paciente = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		Dato ="%s %s %s"% (self.cedula, self.nombre_paci, self.apellido_paci)
		return Dato

class medicamentos(models.Model):
	codigo_med = models.CharField(max_length=10, null=True)
	nombre_med = models.CharField(max_length=50, null=True)
	numero_lote = models.CharField(max_length=20, null=True)
	fecha_elavorado = models.DateField(null=True)
	fecha_vencimiento = models.DateField(null=True)
	tipo = models.CharField(max_length=50, null=True)
	cantidad = models.IntegerField(null=True)
	precio = models.IntegerField(null=True)
	tiempo_registro_medicamentos = models.DateTimeField(auto_now_add=True, auto_now=False)
	actualizado_medicamentos = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		Dato2 ="%s %s"% (self.codigo_med, self.nombre_med)
		return Dato2

class servicios(models.Model):
	codigo_serv = models.IntegerField(null=True)
	nombre_serv = models.CharField(max_length=50, null=True)
	tipo2 = models.CharField(max_length=50, null=True)
	extencion_tlf = models.IntegerField(null=True)
	asistente_serv = models.CharField(max_length=50, null=True)
	tiempo_registro_servicios = models.DateTimeField(auto_now_add=True, auto_now=False)
	actualizado_servicios = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __unicode__(self):
		Dato3 ="%i %s"% (self.codigo_serv, self.nombre_serv)
		return Dato3		

home/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.db import models

# Create your models here.

class login(models.Model):
	username = models.CharField(max_length=25, null=True)
	password = models.CharField(max_length=25, null=True)
	email = models.CharField(max_length=25, null=True)
	first_name = models.CharField(max_length=25, null=True)
	last_name = models.CharField(max_length=25, null=True)

	def __unicode__(self):
		return username

home/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
 
 
class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']
        widgets = {'password': forms.PasswordInput()}

class ChangePasswordForm(forms.Form):
    current_password = forms.CharField(
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Current Password', 'autocomplete': 'off'}))

    new_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'New Password', 'autocomplete': 'off'}))

    confirm_password = forms.CharField(
        min_length=6,
        max_length=64,
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Confirm New Password', 'autocomplete': 'off'}))

home/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.template import Context
from django.template.loader import get_template
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.utils import timezone
from .models import *
from .forms import *

# Create your views here.

def signup(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = SignUpForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
 
            # Process the data in form.cleaned_data
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            email = form.cleaned_data["email"]
            first_name = form.cleaned_data["first_name"]
            last_name = form.cleaned_data["last_name"]
 
            # At this point, user is a User object that has already been saved
            # to the database. You can continue to change its attributes
            # if you want to change other fields.
            user = User.objects.create_user(username, email, password)
            user.first_name = first_name
            user.last_name = last_name
 
            # Save new user attributes
            user.save()
            return HttpResponseRedirect('/signup/success/')    
            #return HttpResponseRedirect(reverse('main.html'))  # Redirect after POST
    else:
        form = SignUpForm()
        
    data = {
        'form': form,
    }
    return render_to_response('signup.html', data, context_instance=RequestContext(request))

def register_success(request):
    return render_to_response('success.html')

@login_required()
def preloader(request):
    return render_to_response('preloader.html', {'user': request.user},
    context_instance=RequestContext(request))

@login_required()
def home(request):
	return render_to_response('home.html', {'user': request.user},
    context_instance=RequestContext(request))

def mision(request):
    return render_to_response('mision.html')

def vision(request):
    return render_to_response('vision.html')

def quienes_somos(request):
    return render_to_response('QuienesSomos.html')

templates/ayuda.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="stylesheet" type="text/css" href="/static/css/fuente.css">
	<link rel="shortcut icon" href="/static/img/logoSMF.ico">
	<link rel="stylesheet" type="text/css" href="/static/css/fontello.css">
	<link rel="stylesheet" type="text/css" href="/static/css/ayuda.css">
	<title>S.I.S.M.E.D.F.A.R</title>
</head>
<body>
	<div class="ajustes">
		<div class="atras">
			<a href="/home/"><h1><</h1></a>
		</div>
		<div class="imprimir">
			<a onclick="javascript:window.print()"><h1 class="icon-reportes"></h1></a>
		</div>
	</div>
	<div class="contenedor">	
		<img src="/static/img/ayuda.png">
	</div>	
</body>
</html>

templates/edit_medicamentos.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="shortcut icon" href="/static/img/logoSMF.ico">
	<link rel="stylesheet" href="/static/css/inicio.css">
	<link rel="stylesheet" href="/static/css/fontello.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fondo.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fuente.css">
	<link rel="stylesheet" href="/static/css/rg_pacientes.css">
	<title>Pacientes</title>
</head>
<body>
	<header>
	{% block usertools %}
		<input type="checkbox" id="btn-menu">
		<label for="btn-menu" class="icon-list-bullet"></label>
		<nav class="menu animated bounceInDown">
			<ul>
				<li><a href="/home/">Inicio<span class="icon-home"></span></a></li>
               
        		{% if user.is_superuser %}
                <li class="submenu"><a href="#">Registros<span class="icon-registro"></span></a>
               	    <ul class="m1">
						<li><a href="/pacientes/">Pacientes</a></li>
						<li><a href="/medicamentos/">Medicamentos</a></li>
						<li><a href="/servicios/">Servicios</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
                </li>
                {% endif %}
                <li class="submenu"><a href="#">Procesos<span class="icon-proceso"></span></a>
                    <ul class="m2">
						<li><a href="#">Inventario</a></li>
						<li><a href="#">Despacho</a></li>
						{% if user.is_superuser %}
						<li><a href="#">Desincorporacion</a></li>
						{% endif %}
						<li><a href="#">Donaciones</a></li>
						<li><a href="#">Intercambios</a></li>
					</ul>
                </li>
				<li class="submenu"><a href="#">Consultas<span class="icon-consultas"></span></a>
				    <ul class="m3">
						<li><a href="/mtr_pacientes/">Pacientes</a></li>
						<li><a href="/mtr_medicamentos/">Medicamentos</a></li>
						<li><a href="/mtr_servicios/">Servicios</a></li>
						<li><a href="#">Archivos</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Reportes<span class="icon-reportes"></span></a>
				    <ul class="m4">
						<li><a href="/reporte_pacientes_pdf/" target="_blanck">Pacientes</a></li>
						{% if user.is_superuser %}
						<li><a href="#" target="_blanck">S.D.M.P.P</a></li>
						{% endif %}
						<li><a href="/reporte_medicamentos_pdf/" target="_blanck">Medicamentos</a></li>
						<li><a href="/change_views/" target="_blanck">Solicitud.DAH</a></li>
						<li><a href="#" target="_blanck">Inventarios</a></li>
						<li><a href="#" target="_blanck">Salidas</a></li>
						<li><a href="#" target="_blanck">Donaciones</a></li>
						<li><a href="#" target="_blanck">Intercambios</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Ayuda<span class="icon-ayuda"></span></a>
				    <ul class="m5">
				    {% if user.is_superuser %}
						<li><a href="/signup/">Nuevos Usuarios</a></li>
					{% endif %}	
						<li><a href="#">Manual de Usuarios</a></li>
					</ul>
				</li>
				<li><a href="/logout/">Logout<span class="icon-logout"></span></a></li>
			</ul>
		</nav>
	{% endblock %}	
	</header>
	<div class="contenido">
	<br>
   	{% block content %}			
		<form class="form-register" method="GET">{% csrf_token %}
			<h1 class="form-titulo">REGISTRAR MEDICAMENTOS</h1>
			<div class="contenedor-input">
				<input maxlength="10" type="text" id="id_codigo_med" name="codigo_med" placeholder="Codigo (*)" class="input-100" required>
				<input maxlength="50" type="text" id="id_nombre_med" name="nombre_med" placeholder="Nombre (*)" class="input-48" required>
            	<input maxlength="10" type="num" id="id_numero_lote" name="numero_lote" placeholder="Numero Lote (*)" class="input-48" required>

				<input type="Text" id="id_fecha_elavorado" name="fecha_elavorado" placeholder="Fecha Elavoración (*)" class="input-48" required>
				<input type="Text" id="id_fecha_vencimiento" name="fecha_vencimiento" placeholder="Fecha Vencimiento (*)" class="input-48" required>

            	<input maxlength="15" type="text" id="id_tipo" name="tipo" placeholder="Tipo (*)" class="input-48" required>
            	<input maxlength="30" type="num" id="id_cantidad" name="cantidad" placeholder="Cantidad (*)" class="input-48" required>
            	<input type="num" id="id_precio" name="precio" placeholder="Precio (*)" class="input-100" required>
            	
            	<input type="submit" onclick='alert("guardado exitosamente")' value="Registrar" class="input-100">
	        </div>
	    </form>
	{% endblock %}    
    </div>
</body>
</html>

templates/edit_pacientes.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="shortcut icon" href="/static/img/logoSMF.ico">
	<link rel="stylesheet" href="/static/css/inicio.css">
	<link rel="stylesheet" href="/static/css/fontello.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fondo.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fuente.css">
	<link rel="stylesheet" href="/static/css/rg_pacientes.css">
	<title>Pacientes</title>
</head>
<body>
	<header>
	{% block usertools %}
		<input type="checkbox" id="btn-menu">
		<label for="btn-menu" class="icon-list-bullet"></label>
		<nav class="menu animated bounceInDown">
			<ul>
				<li><a href="/home/">Inicio<span class="icon-home"></span></a></li>
               
        		{% if user.is_superuser %}
                <li class="submenu"><a href="#">Registros<span class="icon-registro"></span></a>
               	    <ul class="m1">
						<li><a href="/pacientes/">Pacientes</a></li>
						<li><a href="/medicamentos/">Medicamentos</a></li>
						<li><a href="/servicios/">Servicios</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
                </li>
                {% endif %}
                <li class="submenu"><a href="#">Procesos<span class="icon-proceso"></span></a>
                    <ul class="m2">
						<li><a href="#">Inventario</a></li>
						<li><a href="#">Despacho</a></li>
						{% if user.is_superuser %}
						<li><a href="#">Desincorporacion</a></li>
						{% endif %}
						<li><a href="#">Donaciones</a></li>
						<li><a href="#">Intercambios</a></li>
					</ul>
                </li>
				<li class="submenu"><a href="#">Consultas<span class="icon-consultas"></span></a>
				    <ul class="m3">
						<li><a href="/mtr_pacientes/">Pacientes</a></li>
						<li><a href="/mtr_medicamentos/">Medicamentos</a></li>
						<li><a href="/mtr_servicios/">Servicios</a></li>
						<li><a href="#">Archivos</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Reportes<span class="icon-reportes"></span></a>
				    <ul class="m4">
						<li><a href="/reporte_pacientes_pdf/" target="_blanck">Pacientes</a></li>
						{% if user.is_superuser %}
						<li><a href="#" target="_blanck">S.D.M.P.P</a></li>
						{% endif %}
						<li><a href="/reporte_medicamentos_pdf/" target="_blanck">Medicamentos</a></li>
						<li><a href="/change_views/" target="_blanck">Solicitud.DAH</a></li>
						<li><a href="#" target="_blanck">Inventarios</a></li>
						<li><a href="#" target="_blanck">Salidas</a></li>
						<li><a href="#" target="_blanck">Donaciones</a></li>
						<li><a href="#" target="_blanck">Intercambios</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Ayuda<span class="icon-ayuda"></span></a>
				    <ul class="m5">
				    {% if user.is_superuser %}
						<li><a href="/signup/">Nuevos Usuarios</a></li>
					{% endif %}	
						<li><a href="#">Manual de Usuarios</a></li>
					</ul>
				</li>
				<li><a href="/logout/">Logout<span class="icon-logout"></span></a></li>
			</ul>
		</nav>
	{% endblock %}	
	</header>
	<div class="contenido">
	<br>
   	{% block content %}			
		<form class="form-register" method="GET">{% csrf_token %}
			<h1 class="form-titulo">REGISTRAR PACIENTES</h1>
			<div class="contenedor-input">
				<input maxlength="30" type="text" id="id_cedula" name="cedula" placeholder="Cedula" class="input-100" required>
				<input maxlength="30" type="text" id="id_nombre_paci" name="nombre_paci" placeholder="Nombre" class="input-48" required>
            	<input maxlength="30" type="text" id="id_apellido_paci" name="apellido_paci" placeholder="Apellido" class="input-48" required>
				
				<input maxlength="15" type="num" id="id_cod_movil" name="cod_movil" placeholder="Codigo Movil" class="input-48" required>
            	<input maxlength="15" type="num" id="id_movil" name="movil" placeholder="Numero Movil" class="input-48" required>
				
				<input maxlength="15" type="num" id="id_cod_tlf" name="cod_tlf" placeholder="Codigo Teléfono Hbt" class="input-48" required>
            	<input maxlength="30" type="num" id="id_tlf" name="tlf" placeholder="Teléno Habitación" class="input-48" required>

            	<input maxlength="500" type="text" id="id_direccion_paci" name="direccion_paci" placeholder="Direccion de Vivienda" class="input-48" required>
            	<label for="fech_naci">Fecha De Nacimiento</label>
            	<input style="margin-left: 229px; margin-top: -44px;" maxlength="20" type="date" class="input-48" id="id_fech_naci" name="fech_naci" placeholder="Fecha De Nacimiento" required>
            	<input type="submit" onclick='alert("guardado exitosamente")' value="Registrar" class="input-100">
	        </div>
	    </form>
	{% endblock %}    
    </div>
</body>
</html>

templates/rg_medicamentos.html
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<link rel="shortcut icon" href="/static/img/logoSMF.ico">
	<link rel="stylesheet" href="/static/css/inicio.css">
	<link rel="stylesheet" href="/static/css/fontello.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fondo.css">
	<link rel="stylesheet" type="text/css" href="/static/css/fuente.css">
	<link rel="stylesheet" href="/static/css/rg_pacientes.css">
	<title>Pacientes</title>
</head>
<body>
	<header>
	{% block usertools %}
		<input type="checkbox" id="btn-menu">
		<label for="btn-menu" class="icon-list-bullet"></label>
		<nav class="menu animated bounceInDown">
			<ul>
				<li><a href="/home/">Inicio<span class="icon-home"></span></a></li>
               
        		{% if user.is_superuser %}
                <li class="submenu"><a href="#">Registros<span class="icon-registro"></span></a>
               	    <ul class="m1">
						<li><a href="/pacientes/">Pacientes</a></li>
						<li><a href="/medicamentos/">Medicamentos</a></li>
						<li><a href="/servicios/">Servicios</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
                </li>
                {% endif %}
                <li class="submenu"><a href="#">Procesos<span class="icon-proceso"></span></a>
                    <ul class="m2">
						<li><a href="#">Inventario</a></li>
						<li><a href="#">Despacho</a></li>
						<li><a href="#">Desincorporacion</a></li>
						<li><a href="#">Donaciones</a></li>
						<li><a href="#">Intercambios</a></li>
					</ul>
                </li>
				<li class="submenu"><a href="#">Consultas<span class="icon-consultas"></span></a>
				    <ul class="m3">
						<li><a href="/mtr_pacientes/">Pacientes</a></li>
						<li><a href="/mtr_medicamentos/">Medicamentos</a></li>
						<li><a href="#">Servicios</a></li>
						<li><a href="#">Archivos</a></li>
						<li><a href="#">Instituciones</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Reportes<span class="icon-reportes"></span></a>
				    <ul class="m4">
						<li><a href="/reporte_pacientes_pdf/" target="_blanck">Pacientes</a></li>
						{% if user.is_superuser %}
						<li><a href="#" target="_blanck">Veremos...</a></li>
						{% endif %}
						<li><a href="/reporte_medicamentos_pdf/" target="_blanck">Medicamentos</a></li>
						<li><a href="/change_views/" target="_blanck">Solicitud.DAH</a></li>
						<li><a href="#" target="_blanck">Inventarios</a></li>
						<li><a href="#" target="_blanck">Salidas</a></li>
						<li><a href="#" target="_blanck">Donaciones</a></li>
						<li><a href="#" target="_blanck">Intercambios</a></li>
					</ul>
				</li>
				<li class="submenu"><a href="#">Ayuda<span class="icon-ayuda"></span></a>
				    <ul class="m5">
				    {% if user.is_superuser %}
						<li><a href="/signup/">Nuevos Usuarios</a></li>
					{% endif %}	
						<li><a href="#">Manual de Usuarios</a></li>
					</ul>
				</li>
				<li><a href="/logout/">Logout<span class="icon-logout"></span></a></li>
			</ul>
		</nav>
	{% endblock %}	
	</header>
	<div class="contenido">
	<br>
   	{% block content %}			
		<form class="form-register" method="POST">{% csrf_token %}
			<h1 class="form-titulo">REGISTRAR MEDICAMENTOS</h1>
			<div class="contenedor-input">
				<input maxlength="10" type="text" id="id_codigo_med" name="codigo_med" placeholder="Codigo" class="input-100" required>
				<input maxlength="50" type="text" id="id_nombre_med" name="nombre_med" placeholder="Nombre" class="input-48" required>
            	<input maxlength="10" type="num" id="id_numero_lote" name="numero_lote" placeholder="Numero Lote" class="input-48" required>

				<input type="Text" id="id_fecha_elavorado" name="fecha_elavorado" placeholder="Fecha De Elavoración" class="input-48" required>
				<input type="Text" id="id_fecha_vencimiento" name="fecha_vencimiento" placeholder="Fecha De Vencimiento" class="input-48" required>

            	<input maxlength="15" type="text" id="id_tipo" name="tipo" placeholder="Tipo" class="input-48" required>
            	<input maxlength="30" type="num" id="id_cantidad" name="cantidad" placeholder="Cantidad" class="input-48" required>
            	<input type="num" id="id_precio" name="precio" placeholder="Precio" class="input-100" required>
            	
            	<input type="submit" onclick='alert("guardado exitosamente")' value="Registrar" class="input-100">
	        </div>
	    </form>
	{% endblock %}    
    </div>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <link rel="shortcut icon" href="/static/img/logoSMF.ico">
    <link rel="stylesheet" href="/static/css/signup.css">
    <link rel="stylesheet" type="text/css" href="/static/css/fondo.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/fuente.css">
    <script src="js/validar.js"></script>
    <title>farma/Segnup</title>
</head>
<body>
	{% block content %}   
    <form class="form-register" action="{% url 'signup' %}" method="post" onsubmit="return validar();">
    {% csrf_token %}   
        <h2 class="form-titulo animated zoomInDown">REGISTRAR NUEVO USUARIO</h2>
        <div class="contenedor-input animated flipInX">
            <input maxlength="30" type="text" id="id_first_name" name="first_name" placeholder="Nombre (*)" class="input-48" required>
            <input maxlength="30" type="text" id="id_last_name" name="last_name" placeholder="Apellido (*)" class="input-48" required>
            <input maxlength="254" type="email" id="id_email" name="email" placeholder="Ejemplo@email.com (*)" class="input-100" required>
            <input maxlength="30" type="text" id="id_username" name="username" placeholder="Usuario (*)" class="input-48" required>
            <input maxlength="20" type="password" id="id_password" name="password" placeholder="Contraseña (*)" class="input-48" required>
            <input type="submit" value="Registrar" onclick='alert("guardado exitosamente")' class="btn-enviar">
            <p class="form-link animated rubberBand">¿Ya tienes una cuenta? <a href="/">|Ingresa Aqui|</a><a href="/home/">          |Volver|</a></p>
        </div>
    </form>
    {% if form.errors %}<p>{{ form.errors }}</p>{% endif %}
    {% endblock %}
</body>
</html>